export const RESTAURANTS = [
  {
    id: "260218",
    name: "The Exotic Shawarma",
    cloudinaryImageId: "a2feeb23ecc230bd2b17cba73ebd2734",
    locality: "Sri Vasavi Grand Lane",
    areaName: "Mehdipatnam",
    costForTwo: "₹150 for two",
    cuisines: ["Arabian", "Momos", "Salads", "Fast Food"],
    avgRating: 4.3,
    parentId: "18936",
    avgRatingString: "4.3",
    totalRatingsString: "500+",
  },
  {
    id: "56102",
    name: "G Pulla Reddy Sweets",
    cloudinaryImageId: "ebf6ddb2bb68d50ed5af67f5a133a21d",
    locality: "Ambedkar Colony rd",
    areaName: "Mehdipatnam",
    costForTwo: "₹300 for two",
    cuisines: ["Sweets", "Desserts", "Snacks"],
    avgRating: 4.6,
    veg: true,
    parentId: "3767",
    avgRatingString: "4.6",
    totalRatingsString: "5K+",
  },
  {
    id: "725289",
    name: "Mayur pan house",
    cloudinaryImageId: "1b5e469a1040822ff0d6be479f622396",
    locality: "Inner Ring Rd",
    areaName: "Attapur",
    costForTwo: "₹300 for two",
    cuisines: ["Paan"],
    avgRating: 4.3,
    veg: true,
    parentId: "627",
    avgRatingString: "4.3",
    totalRatingsString: "50+",
  },
  {
    id: "30253",
    name: "Agra Sweets Banjara",
    cloudinaryImageId: "nav4ebkoxrwlladx7a5m",
    locality: "Utkoor- Mogdumpur road",
    areaName: "Rambagh Colony",
    costForTwo: "₹250 for two",
    cuisines: ["Sweets", "Desserts", "Chaat", "Snacks", "Beverages"],
    avgRating: 4.3,
    veg: true,
    parentId: "34",
    avgRatingString: "4.3",
  },
  {
    id: "354027",
    name: "Vasireddy Swagruha Foods",
    cloudinaryImageId: "483b96ccaeb3aea13edd659914f82020",
    locality: "kavuri hills",
    areaName: "Madhapur",
    costForTwo: "₹300 for two",
    cuisines: ["Sweets", "Snacks"],
    avgRating: 4.2,
    parentId: "951",
    avgRatingString: "4.2",
    totalRatingsString: "1K+",
  },
  {
    id: "9296",
    name: "Subway",
    cloudinaryImageId: "63178e3e64d503a479f2a2048a474552",
    locality: "Humayun Nagar",
    areaName: "Mehdipatnam",
    costForTwo: "₹350 for two",
    cuisines: ["Salads", "Snacks", "Desserts", "Beverages"],
    avgRating: 3.7,
    parentId: "2",
    avgRatingString: "3.7",
    totalRatingsString: "10K+",
  },
  {
    id: "707258",
    name: "Brown Bear",
    cloudinaryImageId: "02101addd7df8ea75a223b25975c7402",
    locality: "Gumma Konda Colony",
    areaName: "Attapur",
    costForTwo: "₹200 for two",
    cuisines: ["Snacks", "Burgers", "Fast Food"],
    avgRating: 3.7,
    parentId: "18912",
    avgRatingString: "3.7",
    totalRatingsString: "20+",
  },
  {
    id: "491959",
    name: "BOX8 - Desi Meals",
    cloudinaryImageId: "69a061b7e0f951cef2b4947946f94ec6",
    locality: "GUMMA KONDA COLONY",
    areaName: "Attapur",
    costForTwo: "₹250 for two",
    cuisines: ["North Indian", "Biryani", "Thalis", "Home Food"],
    avgRating: 4.2,
    parentId: "10655",
    avgRatingString: "4.2",
    totalRatingsString: "1K+",
  },
  {
    id: "643825",
    name: "WeFit-Bowls, Salads & Sandwiches",
    cloudinaryImageId: "727ee82703c6fa71d1c954ead91dc20d",
    locality: "GUMMA KONDA COLONY",
    areaName: "Attapur",
    costForTwo: "₹250 for two",
    cuisines: ["Healthy Food", "Salads", "Keto", "Snacks"],
    avgRating: 4.3,
    parentId: "355285",
    avgRatingString: "4.3",
    totalRatingsString: "100+",
  },
  {
    id: "347189",
    name: "Chickpet Donne Biryani House",
    cloudinaryImageId: "e6ncbezcldzz6rnxedce",
    locality: "Attapur",
    areaName: "Attapur",
    costForTwo: "₹300 for two",
    cuisines: ["South Indian"],
    avgRating: 3.9,
    parentId: "5634",
    avgRatingString: "3.9",
    totalRatingsString: "1K+",
  },
  {
    id: "622195",
    name: "MOJO Pizza - 2X Toppings",
    cloudinaryImageId: "59b64f9bb67234987652437f21d379c2",
    locality: "Gumma Konda Colony",
    areaName: "Attapur",
    costForTwo: "₹250 for two",
    cuisines: ["Pizzas", "Italian", "Fast Food", "Desserts"],
    avgRating: 4.3,
    parentId: "11329",
    avgRatingString: "4.3",
    totalRatingsString: "500+",
  },
  {
    id: "415908",
    name: "Swiss Castle",
    cloudinaryImageId: "fsspyr7kqdpnhfa8hvbb",
    locality: "Pillar No 75",
    areaName: "Tolichowki",
    costForTwo: "₹200 for two",
    cuisines: ["Bakery", "Sweets", "Desserts"],
    avgRating: 4.5,
    veg: true,
    parentId: "2532",
    avgRatingString: "4.5",
  },
  {
    id: "491964",
    name: "ZAZA Mughal Biryani",
    cloudinaryImageId: "e12f3a72ab92442dc088f803a04d4293",
    locality: "Attapur",
    areaName: "GUMMA KONDA COLONY",
    costForTwo: "₹250 for two",
    cuisines: ["Biryani", "North Indian", "Awadhi"],
    avgRating: 3.7,
    parentId: "22473",
    avgRatingString: "3.7",
    totalRatingsString: "100+",
  },
  {
    id: "681605",
    name: "LeanCrust Pizza- ThinCrust Experts",
    cloudinaryImageId: "9eec061a16f144a434503dfaa984a933",
    locality: "GUMMA KONDA COLONY",
    areaName: "Attapur",
    costForTwo: "₹300 for two",
    cuisines: ["Pizzas", "Italian", "Desserts"],
    avgRating: 4.2,
    parentId: "11216",
    avgRatingString: "4.2",
    totalRatingsString: "100+",
  },
  {
    id: "491960",
    name: "Itminaan Matka Biryani - Slow Cooked",
    cloudinaryImageId: "e165225d26130103fecf1c40f5dc3669",
    locality: "Attapur",
    areaName: "GUMMA KONDA COLONY",
    costForTwo: "₹250 for two",
    cuisines: ["Biryani", "North Indian", "Mughlai"],
    avgRating: 4.1,
    parentId: "107673",
    avgRatingString: "4.1",
    totalRatingsString: "100+",
  },
];
